name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GO
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Run tests and collect coverage
        run: go test -v -covermode=count -coverprofile=coverage.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: brionac626/pipelineinternal
